'use strict';

const SOURCE_KINDS = Object.freeze({
  LAB_SELFTEST: 'LAB_SELFTEST',
  AUTHORIZED_CLIENT_CAPTURE: 'AUTHORIZED_CLIENT_CAPTURE',
  SYNTHETIC_TEST: 'SYNTHETIC_TEST',
  UNVERIFIED_LOCAL: 'UNVERIFIED_LOCAL',
});

const AUTHORIZATION_STATUSES = Object.freeze({
  AUTHORIZED: 'AUTHORIZED',
  UNVERIFIED: 'UNVERIFIED',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
});

const CANDIDATE_CLASSES = Object.freeze({
  OBSERVED_2K17_CANDIDATE: 'OBSERVED_2K17_CANDIDATE',
  INSTRUMENT_SELFTEST: 'INSTRUMENT_SELFTEST',
  SYNTHETIC_TEST: 'SYNTHETIC_TEST',
  UNVERIFIED: 'UNVERIFIED',
});

module.exports = {
  SOURCE_KINDS,
  AUTHORIZATION_STATUSES,
  CANDIDATE_CLASSES,
};
