#!/usr/bin/env node
'use strict';

// Endpoint-id research utility (M001 phase 5). EVIDENCE TOOL ONLY.
//
//   node tools/m001/endpoint-id.js --table <Endpoints2K17.json> [--json]
//   node tools/m001/endpoint-id.js --derive SERVICE:METHOD [...]
//
// Takes the service/method pairs in an endpoint table, computes a fixed, small
// set of candidate transforms, and reports which ids each transform reproduces.
// It does NOT search: no brute force, no dictionary expansion. A transform that
// matches some rows is reported with its match count and is never promoted to a
// universal rule; rows it does not reproduce stay "unexplained".
//
// Caveat that keeps this honest: the table's (id -> URL) pairs are themselves a
// cross-version port (2K19 ids/URLs renamed to /nba/2k17). A CRC match proves
// that the NAME hashes to the ID. It does not prove the 2K17 client uses that
// id for that purpose; only an observed request does.

const Fs = require('node:fs');
const Lib = require('./lib');

const Upper = (Text) => String(Text).toUpperCase();
const Snake = (Text) => String(Text).replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase();
const Bare = (Text) => String(Text).replace(/V?\d+$/i, ''); // GameStatsV4 -> GameStats

// Each transform maps (Service, Method) from the URL to the string that is hashed.
const Transforms = {
    'UPPER(Service:Method)': (S, M) => `${Upper(S)}:${Upper(M)}`,
    'SNAKE(Service):SNAKE(Method)': (S, M) => `${Snake(S)}:${Snake(M)}`,
    'SNAKE(ServiceNoVersion):SNAKE(Method)': (S, M) => `${Snake(Bare(S))}:${Snake(M)}`,
    'Service:Method (as written)': (S, M) => `${S}:${M}`,
    'lower(Service:Method)': (S, M) => `${S}:${M}`.toLowerCase(),
    'UPPER(Service/Method)': (S, M) => `${Upper(S)}/${Upper(M)}`,
    'lower(/service/method)': (S, M) => `/${S}/${M}`.toLowerCase(),
    'SNAKE(Method) only': (S, M) => Snake(M),
};

function PairOf(Url) {
    const Match = /\/nba\/2k\d+\/(.+)$/.exec(String(Url));
    if (!Match) return null;
    const Parts = Match[1].split('/').filter(Boolean);
    if (Parts.length < 2) return null;
    return { Service: Parts.slice(0, -1).join('/'), Method: Parts[Parts.length - 1] };
}

function Analyse(Endpoints) {
    const PerTransform = Object.fromEntries(Object.keys(Transforms).map((Name) => [Name, 0]));
    const Rows = [];
    let CandidateChecked = 0;
    let CandidateOk = 0;
    for (const Endpoint of Endpoints) {
        const Id = Number.parseInt(String(Endpoint.EndpointId), 16) >>> 0;
        const Pair = PairOf(Endpoint.Url);
        const Matched = [];
        if (Pair && !/^Probe2K17$/i.test(Pair.Service)) {
            for (const [Name, Build] of Object.entries(Transforms)) {
                if (Lib.Crc32(Build(Pair.Service, Pair.Method)) === Id) {
                    Matched.push(Name);
                    PerTransform[Name]++;
                }
            }
        }
        // A row may carry an explicit candidate string; verify it instead of trusting it.
        let Candidate = null;
        if (typeof Endpoint.Candidate === 'string') {
            CandidateChecked++;
            const Ok = Lib.Crc32(Endpoint.Candidate) === Id;
            if (Ok) CandidateOk++;
            Candidate = { text: Endpoint.Candidate, reproduces_id: Ok };
        }
        Rows.push({ id: Lib.Hex32(Id), pair: Pair ? `${Pair.Service}:${Pair.Method}` : null, matched: Matched, candidate: Candidate, id_evidence: Endpoint.EndpointIdEvidence || null });
    }
    // Only ids that were read out of an executable can VALIDATE a transform. A row
    // whose id was generated by hashing its own candidate name reproduces
    // trivially; counting it as support would be circular.
    const Independent = Rows.filter((Row) => /^IDA_EXACT/.test(Row.id_evidence || ''));
    const IndependentHit = Independent.filter((Row) => Row.matched.length || Row.candidate?.reproduces_id);
    const Circular = Rows.filter((Row) => Row.candidate && !/^IDA_EXACT/.test(Row.id_evidence || ''));
    const PerTransformIndependent = Object.fromEntries(Object.keys(Transforms).map((Name) => [Name, Independent.filter((Row) => Row.matched.includes(Name)).length]));
    return {
        schema_version: 0,
        kind: 'endpoint-id-derivation-report',
        evidence_class_of_a_match: 'DERIVED (name -> id is reproducible). The id -> purpose link stays REFERENCE until a 2K17 request is OBSERVED.',
        rows: Rows.length,
        validation_set: {
            basis: 'rows whose id is labelled as read from an executable (IDA_EXACT_*); the label is the table author\'s claim and was not re-verified here',
            rows: Independent.length,
            reproduced: IndependentHit.length,
            not_reproduced: Independent.length - IndependentHit.length,
            matches_per_transform: PerTransformIndependent,
        },
        circular_rows: {
            rows: Circular.length,
            note: 'id generated FROM the candidate name, so name->id agreement is guaranteed and proves nothing. Such a row becomes evidence only when the 2K17 client is OBSERVED requesting it.',
            candidate_strings_checked: CandidateChecked,
            candidate_strings_that_do_not_hash_to_their_id: CandidateChecked - CandidateOk,
        },
        matches_per_transform_all_rows: PerTransform,
        universal_rule: IndependentHit.length === Independent.length && Independent.length > 0
            ? 'every validation row reproduced (still not proof for unseen ids)'
            : `NO: name hashing reproduces ${IndependentHit.length} of ${Independent.length} independently-sourced ids; the rest are not explained by any transform tried here`,
        details: Rows,
    };
}

function Main() {
    const Options = Lib.Args(process.argv.slice(2));
    if (Options.derive) {
        const Names = process.argv.slice(process.argv.indexOf('--derive') + 1).filter((Item) => !Item.startsWith('--'));
        for (const Name of Names) console.log(`${Lib.Hex32(Lib.Crc32(Name))}  CRC32("${Name}")  [DERIVED]`);
        return;
    }
    if (!Options.table) throw new Error('usage: endpoint-id.js --table <Endpoints.json> [--json] | --derive NAME [...]');
    const Document = JSON.parse(Fs.readFileSync(Options.table, 'utf8'));
    const Report = Analyse(Document.Endpoints || []);
    if (Options.json) return console.log(JSON.stringify(Report, null, 2));
    const { details, ...Summary } = Report;
    console.log(JSON.stringify(Summary, null, 2));
}

if (require.main === module) {
    try {
        Main();
    } catch (Failure) {
        console.error(`endpoint-id: ${Failure.message}`);
        process.exit(1);
    }
}

module.exports = { Analyse, PairOf, Transforms, Snake };
